// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/net/game.proto

package net

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PPosition struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PPosition) Reset()         { *m = PPosition{} }
func (m *PPosition) String() string { return proto.CompactTextString(m) }
func (*PPosition) ProtoMessage()    {}
func (*PPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad8b26ed7a5e6aa6, []int{0}
}

func (m *PPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PPosition.Unmarshal(m, b)
}
func (m *PPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PPosition.Marshal(b, m, deterministic)
}
func (m *PPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PPosition.Merge(m, src)
}
func (m *PPosition) XXX_Size() int {
	return xxx_messageInfo_PPosition.Size(m)
}
func (m *PPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_PPosition.DiscardUnknown(m)
}

var xxx_messageInfo_PPosition proto.InternalMessageInfo

func (m *PPosition) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PPosition) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PPlayer struct {
	PlayerID             string     `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Position             *PPosition `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PPlayer) Reset()         { *m = PPlayer{} }
func (m *PPlayer) String() string { return proto.CompactTextString(m) }
func (*PPlayer) ProtoMessage()    {}
func (*PPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad8b26ed7a5e6aa6, []int{1}
}

func (m *PPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PPlayer.Unmarshal(m, b)
}
func (m *PPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PPlayer.Marshal(b, m, deterministic)
}
func (m *PPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PPlayer.Merge(m, src)
}
func (m *PPlayer) XXX_Size() int {
	return xxx_messageInfo_PPlayer.Size(m)
}
func (m *PPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_PPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_PPlayer proto.InternalMessageInfo

func (m *PPlayer) GetPlayerID() string {
	if m != nil {
		return m.PlayerID
	}
	return ""
}

func (m *PPlayer) GetPosition() *PPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

func init() {
	proto.RegisterType((*PPosition)(nil), "net.p_position")
	proto.RegisterType((*PPlayer)(nil), "net.p_player")
}

func init() {
	proto.RegisterFile("proto/net/game.proto", fileDescriptor_ad8b26ed7a5e6aa6)
}

var fileDescriptor_ad8b26ed7a5e6aa6 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4b, 0x2d, 0xd1, 0x4f, 0x4f, 0xcc, 0x4d, 0xd5, 0x03, 0x73, 0x85, 0x98, 0xf3,
	0x52, 0x4b, 0x94, 0x34, 0xb8, 0xb8, 0x0a, 0xe2, 0x0b, 0xf2, 0x8b, 0x33, 0x4b, 0x32, 0xf3, 0xf3,
	0x84, 0x78, 0xb8, 0x18, 0x23, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x18, 0x23, 0x40, 0xbc,
	0x48, 0x09, 0x26, 0x08, 0x2f, 0x52, 0x29, 0x98, 0x8b, 0xa3, 0x20, 0xbe, 0x20, 0x27, 0xb1, 0x32,
	0xb5, 0x48, 0x48, 0x8a, 0x8b, 0x23, 0x00, 0xcc, 0xf2, 0x74, 0x01, 0x2b, 0xe7, 0x0c, 0x82, 0xf3,
	0x85, 0xb4, 0xb9, 0x38, 0x02, 0xa0, 0xe6, 0x81, 0x35, 0x73, 0x1b, 0xf1, 0xeb, 0xe5, 0xa5, 0x96,
	0xe8, 0x21, 0xac, 0x09, 0x82, 0x2b, 0x70, 0xe2, 0x8e, 0xe2, 0x84, 0xbb, 0x2d, 0x89, 0x0d, 0xcc,
	0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x75, 0xe3, 0x09, 0x1a, 0xaf, 0x00, 0x00, 0x00,
}
