// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/net/sys.proto

package net

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MHeartbeatTos struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MHeartbeatTos) Reset()         { *m = MHeartbeatTos{} }
func (m *MHeartbeatTos) String() string { return proto.CompactTextString(m) }
func (*MHeartbeatTos) ProtoMessage()    {}
func (*MHeartbeatTos) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ee6ab73fc5802e, []int{0}
}

func (m *MHeartbeatTos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MHeartbeatTos.Unmarshal(m, b)
}
func (m *MHeartbeatTos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MHeartbeatTos.Marshal(b, m, deterministic)
}
func (m *MHeartbeatTos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MHeartbeatTos.Merge(m, src)
}
func (m *MHeartbeatTos) XXX_Size() int {
	return xxx_messageInfo_MHeartbeatTos.Size(m)
}
func (m *MHeartbeatTos) XXX_DiscardUnknown() {
	xxx_messageInfo_MHeartbeatTos.DiscardUnknown(m)
}

var xxx_messageInfo_MHeartbeatTos proto.InternalMessageInfo

type MHeartbeatToc struct {
	Timestamp            int32    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MHeartbeatToc) Reset()         { *m = MHeartbeatToc{} }
func (m *MHeartbeatToc) String() string { return proto.CompactTextString(m) }
func (*MHeartbeatToc) ProtoMessage()    {}
func (*MHeartbeatToc) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ee6ab73fc5802e, []int{1}
}

func (m *MHeartbeatToc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MHeartbeatToc.Unmarshal(m, b)
}
func (m *MHeartbeatToc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MHeartbeatToc.Marshal(b, m, deterministic)
}
func (m *MHeartbeatToc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MHeartbeatToc.Merge(m, src)
}
func (m *MHeartbeatToc) XXX_Size() int {
	return xxx_messageInfo_MHeartbeatToc.Size(m)
}
func (m *MHeartbeatToc) XXX_DiscardUnknown() {
	xxx_messageInfo_MHeartbeatToc.DiscardUnknown(m)
}

var xxx_messageInfo_MHeartbeatToc proto.InternalMessageInfo

func (m *MHeartbeatToc) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*MHeartbeatTos)(nil), "net.m_heartbeat_tos")
	proto.RegisterType((*MHeartbeatToc)(nil), "net.m_heartbeat_toc")
}

func init() {
	proto.RegisterFile("proto/net/sys.proto", fileDescriptor_54ee6ab73fc5802e)
}

var fileDescriptor_54ee6ab73fc5802e = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4b, 0x2d, 0xd1, 0x2f, 0xae, 0x2c, 0xd6, 0x03, 0xf3, 0x84, 0x98, 0xf3, 0x52,
	0x4b, 0x94, 0x04, 0xb9, 0xf8, 0x73, 0xe3, 0x33, 0x52, 0x13, 0x8b, 0x4a, 0x92, 0x52, 0x13, 0x4b,
	0xe2, 0x4b, 0xf2, 0x8b, 0x95, 0xf4, 0xd1, 0x85, 0x92, 0x85, 0x64, 0xb8, 0x38, 0x4b, 0x32, 0x73,
	0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x10, 0x02, 0x49,
	0x6c, 0x60, 0xf3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xa2, 0x53, 0x1a, 0x66, 0x00,
	0x00, 0x00,
}
