// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/map.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	net "proto/net"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// @brief map msg
type PMapMsg struct {
	Player               *net.PPlayer `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"`
	MsgId                int32        `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PMapMsg) Reset()         { *m = PMapMsg{} }
func (m *PMapMsg) String() string { return proto.CompactTextString(m) }
func (*PMapMsg) ProtoMessage()    {}
func (*PMapMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3f9561ce5703a75, []int{0}
}

func (m *PMapMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMapMsg.Unmarshal(m, b)
}
func (m *PMapMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMapMsg.Marshal(b, m, deterministic)
}
func (m *PMapMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMapMsg.Merge(m, src)
}
func (m *PMapMsg) XXX_Size() int {
	return xxx_messageInfo_PMapMsg.Size(m)
}
func (m *PMapMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PMapMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PMapMsg proto.InternalMessageInfo

func (m *PMapMsg) GetPlayer() *net.PPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PMapMsg) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *PMapMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PMapMsg)(nil), "rpc.p_map_msg")
}

func init() {
	proto.RegisterFile("rpc/map.proto", fileDescriptor_d3f9561ce5703a75)
}

var fileDescriptor_d3f9561ce5703a75 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2a, 0x48, 0xd6,
	0xcf, 0x4d, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x96, 0xe2,
	0xcb, 0x4b, 0x2d, 0xd1, 0x4f, 0x4f, 0xcc, 0x4d, 0x85, 0x08, 0x2a, 0xc5, 0x72, 0x71, 0x16, 0xc4,
	0xe7, 0x26, 0x16, 0xc4, 0xe7, 0x16, 0xa7, 0x0b, 0xa9, 0x72, 0xb1, 0x05, 0xe4, 0x24, 0x56, 0xa6,
	0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xea, 0xe5, 0xa5, 0x96, 0xe8, 0x15, 0xc4,
	0x17, 0x80, 0x05, 0x83, 0xa0, 0x92, 0x42, 0xa2, 0x5c, 0x6c, 0xb9, 0xc5, 0xe9, 0xf1, 0x99, 0x29,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0xac, 0xb9, 0xc5, 0xe9, 0x9e, 0x29, 0x42, 0x42, 0x5c,
	0x2c, 0x2e, 0x89, 0x25, 0x89, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x13, 0x6b,
	0x14, 0xc8, 0xd6, 0x24, 0x36, 0xb0, 0x65, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x9a,
	0x7d, 0x60, 0x92, 0x00, 0x00, 0x00,
}
