// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/test.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// @brief base_score_info
type TestEchoACK struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestEchoACK) Reset()         { *m = TestEchoACK{} }
func (m *TestEchoACK) String() string { return proto.CompactTextString(m) }
func (*TestEchoACK) ProtoMessage()    {}
func (*TestEchoACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1be4f405dbf6e9, []int{0}
}

func (m *TestEchoACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEchoACK.Unmarshal(m, b)
}
func (m *TestEchoACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEchoACK.Marshal(b, m, deterministic)
}
func (m *TestEchoACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEchoACK.Merge(m, src)
}
func (m *TestEchoACK) XXX_Size() int {
	return xxx_messageInfo_TestEchoACK.Size(m)
}
func (m *TestEchoACK) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEchoACK.DiscardUnknown(m)
}

var xxx_messageInfo_TestEchoACK proto.InternalMessageInfo

func (m *TestEchoACK) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *TestEchoACK) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*TestEchoACK)(nil), "rpc.TestEchoACK")
}

func init() {
	proto.RegisterFile("rpc/test.proto", fileDescriptor_bf1be4f405dbf6e9)
}

var fileDescriptor_bf1be4f405dbf6e9 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2a, 0x48, 0xd6,
	0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56,
	0x32, 0xe5, 0xe2, 0x0e, 0x49, 0x2d, 0x2e, 0x71, 0x4d, 0xce, 0xc8, 0x77, 0x74, 0xf6, 0x16, 0x12,
	0xe0, 0x62, 0xf6, 0x2d, 0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x44,
	0xb8, 0x58, 0xc3, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x20, 0x9c,
	0x24, 0x36, 0xb0, 0x11, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x2e, 0x6b, 0x6a, 0x54,
	0x00, 0x00, 0x00,
}
